/*Copyright (C) 2016, IIT Ropar
This file is part of Destello.

    Destello is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Destello is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
Authors: Sourodeep, Gian, Neeraj (change the order according to file)
Contact: destello-support@gmail.com
 * */

package destello2;

import java.util.ArrayList;
import java.util.Arrays;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BreakPoint.java
 *
 * Created on 5 Jun, 2016, 12:23:34 PM
 */

/**
 *
 * @author SOURODEEP
 */
public class BreakPoint extends javax.swing.JFrame {

    /**
	 * 
	 */
	 static ArrayList<Long> bkpt = new ArrayList<Long>();
	   static Long[] list= new Long[bkpt.size()] ;
	   static Long[] arry=new Long[10]; 
	//DestelloDebugger obj= new DestelloDebugger();

	private static final long serialVersionUID = 1L;

    /** Creates new form BreakPoint */
    public BreakPoint() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SetBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        OkayBtn = new javax.swing.JButton();

        setTitle("Breakpoint");
        setName("Breakpoint"); // NOI18N

        bkTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter Breakpoint");

        SetBtn.setText("Set");
        SetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
				SetBtnActionPerformed(evt);
            }
        });

        ClearBtn.setText("Clear");
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                ClearBtnActionPerformed(evt);
            }
        });

        OkayBtn.setText("Okay");
        OkayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               OkayBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
						.addComponent(SetBtn)
                        .addGap(65, 65, 65)
						.addComponent(ClearBtn)
                        .addGap(54, 54, 54)
                        .addComponent(OkayBtn)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetBtn)
                    .addComponent(ClearBtn)
                    .addComponent(OkayBtn))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bkTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkTFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bkTFActionPerformed

    private void OkayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    BreakpointMark();
    FileAddress. obj.reset(false);
    dispose();
   
    }//GEN-LAST:event_OkayBtnActionPerformed

    private void SetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String s = bkTF.getText();
         long value = Long.decode(s);
         Long value1= new Long(value);
         
             bkpt.add(value1);
              arry= bkpt.toArray(list);
			  bkTF.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = bkTF.getText();
         long ind = Long.parseLong(s);
         bkpt.removeAll(Arrays.asList(ind));
		list = bkpt.toArray(list);
        arry= bkpt.toArray(list);
        bkTF.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void BreakpointMark()
    {
    	String[] lines = home.disTP.getText().split("\n");
    	for(int i=0;i<lines.length ;i++)
    	{
    		System.out.println(" lines "+"\n"+ lines[i]);
    	}
    	int size = lines.length;
    	int bkptsize = bkpt.size();
    	String DissView ="";
    	String currLine="";
    	
    	for(int i=0;i<bkptsize;i++)
    	{
    		long m = arry[i];
    		int k = (int) m;
    		int j = ((k - (int)(FileAddress.obj.startingPC))/4) -1;
    		System.out.println(" value bk index "+j);

    		String str1 = lines[j];
    		String str2 = str1.replace(" 0x","*0x");
    		lines[j] = str2;
    	}
    	home.disTP.setText(" ");
    	for(int l = 0;l<size;l++)
    	{
    		currLine=lines[l]+"\n";
    		DissView= DissView+ currLine;
    		 
    	}
    	home.disTP.setText(DissView);
    	//home.disTA.setCaret(lines);
    }


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreakPoint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bkTF;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JButton OkayBtn;
    private javax.swing.JButton SetBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
