/*Copyright (C) 2016, IIT Ropar
This file is part of Destello.

    Destello is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Destello is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
Authors: Sourodeep, Gian, Neeraj (change the order according to file)
Contact: destello-support@gmail.com
 * */

package destello2;

import java.awt.Color;
import java.io.IOException;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileAddress.java
 *
 * Created on 8 Jun, 2016, 6:48:06 PM
 */

/**
 *
 * @author SOURODEEP
 */
public class FileAddress extends javax.swing.JFrame {

    /**
	 * 
	 */
	public static DestelloDebugger obj = new DestelloDebugger();
//	home homeObj=new home();
	private static final long serialVersionUID = 1L;
	/** Creates new form FileAddress */
    public FileAddress() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddressTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        OkayBtn = new javax.swing.JButton();

        jLabel1.setText("Enter The Complete Path of The Hex File ");

        OkayBtn.setText("Okay");
        OkayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					OkayBtnActionPerformed(evt);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(OkayBtn)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(66, 66, 66)
                .addComponent(OkayBtn)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkayBtnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_OkayBtnActionPerformed
        String adres = AddressTF.getText();
        obj.reset(true);
        obj.loadInstMemory(adres);
        printDisView();
  
     home.PrintRegister();
     home.mem.memoryView();
        dispose();

    }//GEN-LAST:event_OkayBtnActionPerformed

 public void printDisView()
 {
     long q =  obj.startingPC + 4;
     System.out.println(" Starting PC in GUI "+ q);
        String  dissassembly[];
      dissassembly = obj.disassemblyView(q-4);
   
     long r = obj.cycles;
     String disView="";
     String currDissLine="";
     for (int i=0;i<r;i++){
     String s1 =   String.format("%08X",q);
     String s2 =  dissassembly[i];
         currDissLine = "  0x"+s1+"\t \t"+s2+"\n";
         disView = disView+currDissLine;
     q=q+4;
     }
     home.disTP.setText(disView );
 }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileAddress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTF;
    private javax.swing.JButton OkayBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}


