package destello2;


	import java.util.ArrayList;
	import java.awt.*;
	import java.awt.event.*;
	import javax.swing.*;
	import javax.swing.border.*;
	import javax.swing.text.AttributeSet;
	import javax.swing.text.SimpleAttributeSet;
	import javax.swing.text.StyleConstants;
	import javax.swing.text.StyleContext;

	/*
	 * To change this template, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/*
	 * home.java
	 *
	 * Created on 4 Jun, 2016, 4:56:09 PM
	 */

	/**
	 *
	 * @author SOURODEEP
	 */

	public class home extends javax.swing.JFrame {
		private static final long serialVersionUID = 1L;
		BreakPoint h=new BreakPoint();
		 
	       Long[] ary = {0L};
		
	    /** Creates new f[]orm home */

	    public home() {
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        EnterCodeBtn = new javax.swing.JButton();
	        RunBtn = new javax.swing.JButton();
	        BkptBtn = new javax.swing.JButton();
	        ContBtn = new javax.swing.JButton();
	        StopBtn = new javax.swing.JButton();
	        StepBtn = new javax.swing.JButton();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jScrollPane20 = new javax.swing.JScrollPane();
	        disTP = new javax.swing.JTextPane();
	        jPanel3 = new javax.swing.JPanel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();
	        jLabel9 = new javax.swing.JLabel();
	        jLabel10 = new javax.swing.JLabel();
	        jLabel11 = new javax.swing.JLabel();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel13 = new javax.swing.JLabel();
	        jLabel14 = new javax.swing.JLabel();
	        jLabel15 = new javax.swing.JLabel();
	        jLabel16 = new javax.swing.JLabel();
	        jLabel17 = new javax.swing.JLabel();
	        jLabel18 = new javax.swing.JLabel();
	        jLabel19 = new javax.swing.JLabel();
	        jLabel20 = new javax.swing.JLabel();
	        jLabel21 = new javax.swing.JLabel();
	        jLabel22 = new javax.swing.JLabel();
	        jLabel24 = new javax.swing.JLabel();
	        jScrollPane3 = new javax.swing.JScrollPane();
	        R1TP = new javax.swing.JTextPane();
	        jScrollPane4 = new javax.swing.JScrollPane();
	        R2TP = new javax.swing.JTextPane();
	        jScrollPane5 = new javax.swing.JScrollPane();
	        R3TP = new javax.swing.JTextPane();
	        jScrollPane6 = new javax.swing.JScrollPane();
	        R4TP = new javax.swing.JTextPane();
	        jScrollPane7 = new javax.swing.JScrollPane();
	        R5TP = new javax.swing.JTextPane();
	        jScrollPane8 = new javax.swing.JScrollPane();
	        R11TP = new javax.swing.JTextPane();
	        jScrollPane9 = new javax.swing.JScrollPane();
	        R10TP = new javax.swing.JTextPane();
	        jScrollPane10 = new javax.swing.JScrollPane();
	        R9TP = new javax.swing.JTextPane();
	        jScrollPane11 = new javax.swing.JScrollPane();
	        R8TP = new javax.swing.JTextPane();
	        jScrollPane12 = new javax.swing.JScrollPane();
	        R7TP = new javax.swing.JTextPane();
	        jScrollPane13 = new javax.swing.JScrollPane();
	        R6TP = new javax.swing.JTextPane();
	        jScrollPane14 = new javax.swing.JScrollPane();
	        R12TP = new javax.swing.JTextPane();
	        jScrollPane15 = new javax.swing.JScrollPane();
	        R13TP = new javax.swing.JTextPane();
	        jScrollPane16 = new javax.swing.JScrollPane();
	        SPTP = new javax.swing.JTextPane();
	        jScrollPane17 = new javax.swing.JScrollPane();
	        RATP = new javax.swing.JTextPane();
	        jScrollPane18 = new javax.swing.JScrollPane();
	        PCTP = new javax.swing.JTextPane();
	        jScrollPane19 = new javax.swing.JScrollPane();
	        PSWTP = new javax.swing.JTextPane();
	        R0TF = new javax.swing.JTextField();
	        jPanel4 = new javax.swing.JPanel();
	        jLabel2 = new javax.swing.JLabel();
	        jScrollPane2 = new javax.swing.JScrollPane();
	        MemTA = new javax.swing.JTextArea();
	        jPanel5 = new javax.swing.JPanel();
	        jLabel3 = new javax.swing.JLabel();
	        jTextField19 = new javax.swing.JTextField();
	        jLabel4 = new javax.swing.JLabel();
	        MemValueBtn = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

	        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        EnterCodeBtn.setText("Enter Code");
	        EnterCodeBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                EnterCodeBtnActionPerformed(evt);
	            }
	        });

	        RunBtn.setText("Run");
	        RunBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                RunBtnActionPerformed(evt);
	            }
	        });

	        BkptBtn.setText("Breakpoint");
	        BkptBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                BkptBtnActionPerformed(evt);
	            }
	        });

	        ContBtn.setText("Continue");
	        ContBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                ContBtnActionPerformed(evt);
	            }
	        });

	        StopBtn.setText("Stop");

	        StepBtn.setText("Step");
	        StepBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                StepBtnActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
	        jPanel1.setLayout(jPanel1Layout);
	        jPanel1Layout.setHorizontalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel1Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(EnterCodeBtn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(RunBtn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(BkptBtn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(ContBtn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addComponent(StopBtn)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(StepBtn)
	                .addContainerGap())
	        );
	        jPanel1Layout.setVerticalGroup(
	            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(EnterCodeBtn)
	                    .addComponent(RunBtn)
	                    .addComponent(BkptBtn)
	                    .addComponent(ContBtn)
	                    .addComponent(StopBtn)
	                    .addComponent(StepBtn))
	                .addContainerGap())
	        );

	        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        jLabel1.setText("DISASSEMBLY VIEW");

	        jScrollPane20.setViewportView(disTP);

	        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel2Layout.createSequentialGroup()
	                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(179, 179, 179)
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel2Layout.createSequentialGroup()
	                        .addGap(35, 35, 35)
	                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap(62, Short.MAX_VALUE))
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jLabel1)
	                .addGap(33, 33, 33)
	                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(28, 28, 28))
	        );

	        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        jLabel5.setText("R0");

	        jLabel6.setText("R1");

	        jLabel7.setText("R2");

	        jLabel8.setText("R3");

	        jLabel9.setText("R4");

	        jLabel10.setText("R5");

	        jLabel11.setText("R6");

	        jLabel12.setText("R7");

	        jLabel13.setText("R8");

	        jLabel14.setText("R9");

	        jLabel15.setText("R10");

	        jLabel16.setText("R11");

	        jLabel17.setText("R12");

	        jLabel18.setText("R13");

	        jLabel19.setText("SP");

	        jLabel20.setText("RA");

	        jLabel21.setText("PC");

	        jLabel22.setText("PSW");

	        jLabel24.setText("REGISTER VIEW");

	        jScrollPane3.setViewportView(R1TP);

	        jScrollPane4.setViewportView(R2TP);

	        jScrollPane5.setViewportView(R3TP);

	        jScrollPane6.setViewportView(R4TP);

	        jScrollPane7.setViewportView(R5TP);

	        jScrollPane8.setViewportView(R11TP);

	        jScrollPane9.setViewportView(R10TP);

	        jScrollPane10.setViewportView(R9TP);

	        jScrollPane11.setViewportView(R8TP);

	        jScrollPane12.setViewportView(R7TP);

	        jScrollPane13.setViewportView(R6TP);

	        jScrollPane14.setViewportView(R12TP);

	        jScrollPane15.setViewportView(R13TP);

	        jScrollPane16.setViewportView(SPTP);

	        jScrollPane17.setViewportView(RATP);

	        jScrollPane18.setViewportView(PCTP);

	        jScrollPane19.setViewportView(PSWTP);

	        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGap(42, 42, 42)
	                        .addComponent(jLabel5))
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGap(34, 34, 34)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabel10)
	                            .addComponent(jLabel8)
	                            .addComponent(jLabel9)
	                            .addComponent(jLabel6)
	                            .addComponent(jLabel7))))
	                .addGap(31, 31, 31)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(R0TF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGap(56, 56, 56)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabel12)
	                                    .addComponent(jLabel11)
	                                    .addComponent(jLabel13)
	                                    .addComponent(jLabel14)
	                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
	                                .addGap(6, 6, 6))
	                            .addComponent(jLabel16)))
	                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGap(26, 26, 26)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabel17)
	                            .addComponent(jLabel18)
	                            .addComponent(jLabel19)
	                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                .addComponent(jLabel21)
	                                .addComponent(jLabel20)))
	                        .addGap(32, 32, 32)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
	                            .addComponent(jScrollPane18)
	                            .addComponent(jScrollPane17)
	                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane15, javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGap(18, 18, 18)
	                        .addComponent(jLabel22)
	                        .addGap(37, 37, 37)
	                        .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
	                .addGap(68, 68, 68))
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addGap(171, 171, 171)
	                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(346, Short.MAX_VALUE))
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel3Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel24)
	                .addGap(14, 14, 14)
	                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                                    .addComponent(jLabel5)
	                                    .addComponent(jLabel11)
	                                    .addComponent(R0TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGap(8, 8, 8))
	                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addComponent(jLabel12)
	                                        .addGap(8, 8, 8)
	                                        .addComponent(jLabel18)))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabel13)
	                                .addGap(34, 34, 34)
	                                .addComponent(jLabel14)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addComponent(jLabel20)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                        .addComponent(jLabel15))
	                                    .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addComponent(jLabel21)
	                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
	                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                                .addComponent(jLabel16)
	                                                .addGap(6, 6, 6))
	                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                        .addGap(18, 18, 18)
	                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jLabel6)
	                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGap(34, 34, 34)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel7))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(8, 8, 8)
	                                        .addComponent(jLabel8))
	                                    .addGroup(jPanel3Layout.createSequentialGroup()
	                                        .addGap(20, 20, 20)
	                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel9))
	                                .addGap(18, 18, 18)
	                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                    .addGroup(jPanel3Layout.createSequentialGroup()
	                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(29, 29, 29)
	                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(20, 20, 20)
	                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(16, 16, 16)
	                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(jPanel3Layout.createSequentialGroup()
	                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                                    .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                    .addComponent(jLabel19))
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                .addComponent(jLabel22)))))
	                .addGap(22, 22, 22))
	        );

	        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        jLabel2.setText("MEMORY VIEW");

	        MemTA.setColumns(20);
	        MemTA.setRows(5);
	        MemTA.setText("ADDRESS\t\t\t\tDATA");
	        jScrollPane2.setViewportView(MemTA);

	        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
	        jPanel4.setLayout(jPanel4Layout);
	        jPanel4Layout.setHorizontalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
	                .addContainerGap(233, Short.MAX_VALUE)
	                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(197, 197, 197))
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addGap(33, 33, 33)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(26, Short.MAX_VALUE))
	        );
	        jPanel4Layout.setVerticalGroup(
	            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel4Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel2)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(142, 142, 142))
	        );

	        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

	        jLabel3.setText("PERFORMANCE VIEW");

	        jTextField19.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField19ActionPerformed(evt);
	            }
	        });

	        jLabel4.setText("CYCLES");

	        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
	        jPanel5.setLayout(jPanel5Layout);
	        jPanel5Layout.setHorizontalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel5Layout.createSequentialGroup()
	                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(jPanel5Layout.createSequentialGroup()
	                        .addGap(155, 155, 155)
	                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(jPanel5Layout.createSequentialGroup()
	                        .addGap(139, 139, 139)
	                        .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addComponent(jLabel4)))
	                .addContainerGap(197, Short.MAX_VALUE))
	        );
	        jPanel5Layout.setVerticalGroup(
	            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(jPanel5Layout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(jLabel3)
	                .addGap(18, 18, 18)
	                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabel4))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        MemValueBtn.setText("Read/Write Memory");
	        MemValueBtn.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                MemValueBtnActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(63, 63, 63)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(MemValueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(306, 306, 306)
	                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(154, 154, 154)
	                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(63, 63, 63)
	                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
	                .addContainerGap(67, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(27, 27, 27)
	                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(59, 59, 59))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
	                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGap(39, 39, 39)
	                        .addComponent(MemValueBtn)))
	                .addGap(248, 248, 248))
	        );

	        pack();
	    }// </editor-fold>//GEN-END:initComponents
	    DestelloDebugger p = new DestelloDebugger();
	      
	
	    private void StepBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepBtnActionPerformed
	    	Long Array[] = BreakPoint.list;
	    	p.debug(Array,false,true);
   PrintRegister();
	 	     
	}//GEN-LAST:event_StepBtnActionPerformed

	    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
	        // TODO add your handling code here:
	    }//GEN-LAST:event_jTextField19ActionPerformed

	    private void EnterCodeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterCodeBtnActionPerformed
	        // TODO add your handling code here:
	                    FileAddress f = new FileAddress();
	                    f.setVisible(true);

	}//GEN-LAST:event_EnterCodeBtnActionPerformed

	    private void BkptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkptBtnActionPerformed
	       BreakPoint b = new BreakPoint();
	       b.setVisible(true);
	       
	    }//GEN-LAST:event_BkptBtnActionPerformed

	    private void MemValueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemValueBtnActionPerformed
	                MemInputButton m = new MemInputButton();
	                m.setVisible(true);
	                
	    }//GEN-LAST:event_MemValueBtnActionPerformed
	 
	
		
		  
	    private void RunBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunBtnActionPerformed
	        // TODO add your handling code here:
	  
	     p.debug(ary, true, false);
	   
	      
	        long cur = p.currentPC;
	    
	    
         PrintRegister();
	     


	    }//GEN-LAST:event_RunBtnActionPerformed

	    private void ContBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContBtnActionPerformed
	    	Long Array2[] = BreakPoint.a;
	    	  for(int i=0;i<Array2.length;i++){
	              System.out.println(Array2[i]);}
	     
	        p.debug(Array2,true, false);
	        PrintRegister();
		     
	    }//GEN-LAST:event_ContBtnActionPerformed
    private void PrintRegister(){
        for(int i=0;i<18;i++)
 		    {
 		        long l = p.getRegisterValue(i);
 		            //  System.out.println(""+l+","+i);
 		        switch(i)
 		        {

 		            case 0:
 		                R0TF.setText(String.format("%08X",l));
 		            break;
 		            case 1: R1TP.setText(String.format("%08X",l));
 		            break;
 		            case 2: R2TP.setText(String.format("%08X",l));
 		            break;
 		            case 3: R3TP.setText(String.format("%08X",l));
 		            break;
 		            case 4: R4TP.setText(String.format("%08X",l));
 		            case 5: R5TP.setText(String.format("%08X",l));
 		            case 6: R6TP.setText(String.format("%08X",l));
 		            case 7: R7TP.setText(String.format("%08X",l));
 		            case 8: R8TP.setText(String.format("%08X",l));
 		            case 9: R9TP.setText(String.format("%08X",l));
 		            case 10: R10TP.setText(String.format("%08X",l));
 		            case 11: R11TP.setText(String.format("%08X",l));
 		            case 12: R12TP.setText(String.format("%08X",l));
 		            case 13: R13TP.setText(String.format("%08X",l));
 		            case 14: SPTP.setText(String.format("%08X",l));
 		            case 15: RATP.setText(String.format("%08X",l));
 		            case 16: PCTP.setText(String.format("%08X",l));
 		            case 17: PSWTP.setText(String.format("%08X",l));
 		        }
 		     }
    }
	    /**
	    * @param args the command line arguments
	    */
	    public static void main(String args[]) {
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new home().setVisible(true);
	            }
	        });
	    }

	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton BkptBtn;
	    private javax.swing.JButton ContBtn;
	    private javax.swing.JButton EnterCodeBtn;
	    public static javax.swing.JTextArea MemTA;
	    private javax.swing.JButton MemValueBtn;
	    private javax.swing.JTextPane PCTP;
	    private javax.swing.JTextPane PSWTP;
	    private javax.swing.JTextField R0TF;
	    private javax.swing.JTextPane R10TP;
	    private javax.swing.JTextPane R11TP;
	    private javax.swing.JTextPane R12TP;
	    private javax.swing.JTextPane R13TP;
	    private javax.swing.JTextPane R1TP;
	    private javax.swing.JTextPane R2TP;
	    private javax.swing.JTextPane R3TP;
	    private javax.swing.JTextPane R4TP;
	    private javax.swing.JTextPane R5TP;
	    private javax.swing.JTextPane R6TP;
	    private javax.swing.JTextPane R7TP;
	    private javax.swing.JTextPane R8TP;
	    private javax.swing.JTextPane R9TP;
	    private javax.swing.JTextPane RATP;
	    private javax.swing.JButton RunBtn;
	    private javax.swing.JTextPane SPTP;
	    private javax.swing.JButton StepBtn;
	    private javax.swing.JButton StopBtn;
	    public static javax.swing.JTextPane disTP;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel14;
	    private javax.swing.JLabel jLabel15;
	    private javax.swing.JLabel jLabel16;
	    private javax.swing.JLabel jLabel17;
	    private javax.swing.JLabel jLabel18;
	    private javax.swing.JLabel jLabel19;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel20;
	    private javax.swing.JLabel jLabel21;
	    private javax.swing.JLabel jLabel22;
	    private javax.swing.JLabel jLabel24;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JPanel jPanel2;
	    private javax.swing.JPanel jPanel3;
	    private javax.swing.JPanel jPanel4;
	    private javax.swing.JPanel jPanel5;
	    private javax.swing.JScrollPane jScrollPane10;
	    private javax.swing.JScrollPane jScrollPane11;
	    private javax.swing.JScrollPane jScrollPane12;
	    private javax.swing.JScrollPane jScrollPane13;
	    private javax.swing.JScrollPane jScrollPane14;
	    private javax.swing.JScrollPane jScrollPane15;
	    private javax.swing.JScrollPane jScrollPane16;
	    private javax.swing.JScrollPane jScrollPane17;
	    private javax.swing.JScrollPane jScrollPane18;
	    private javax.swing.JScrollPane jScrollPane19;
	    private javax.swing.JScrollPane jScrollPane2;
	    private javax.swing.JScrollPane jScrollPane20;
	    private javax.swing.JScrollPane jScrollPane3;
	    private javax.swing.JScrollPane jScrollPane4;
	    private javax.swing.JScrollPane jScrollPane5;
	    private javax.swing.JScrollPane jScrollPane6;
	    private javax.swing.JScrollPane jScrollPane7;
	    private javax.swing.JScrollPane jScrollPane8;
	    private javax.swing.JScrollPane jScrollPane9;
	    private javax.swing.JTextField jTextField19;
	    // End of variables declaration//GEN-END:variables

	}



