/*Copyright (C) 2016, IIT Ropar
This file is part of Destello.

    Destello is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Destello is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
Authors: Sourodeep, Gian, Neeraj (change the order according to file)
Contact: destello-support@gmail.com
 * */

package destello2;

	/*
	 * To change this template, choose Tools | Templates
	 * and open the template in the editor.
	 */

	/*
	 * MemInputButton.java
	 *
	 * Created on 5 Jun, 2016, 12:19:19 PM
	 */

	/**
	 *
	 * @author SOURODEEP
	 */
	public class MemInputButton extends javax.swing.JFrame {

	    /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		/** Creates new form MemInputButton */
	    public MemInputButton() {
	        initComponents();
	    }

	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MemTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ReadBtn = new javax.swing.JButton();
        WriteBtn = new javax.swing.JButton();
        DataTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("EnterStarting  Memory Address");

        jLabel2.setText("Bytes");

        ReadBtn.setText("Read");
        ReadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadBtnActionPerformed(evt);
            }
        });

        WriteBtn.setText("Write");
        WriteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteBtnActionPerformed(evt);
            }
        });

        DataTF.setEditable(false);
        DataTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTFMouseClicked(evt);
            }
        });

        jLabel3.setText("Data Value");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                        .addComponent(ReadBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(WriteBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DataTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MemTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MemTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadBtn)
                    .addComponent(WriteBtn))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        DestelloDebugger obj = new DestelloDebugger();
	    private void DataTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTFMouseClicked
	        // TODO add your handling code here:
	       DataTF.setEditable(true);
	       
	}//GEN-LAST:event_DataTFMouseClicked

        private void ReadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadBtnActionPerformed

	       // TODO add your handling code here:
	        String s = MemTF.getText();
	        String memView="";
	        String currView="";
	        long l = Long.parseLong(s, 16);
	        home.MemTA.setText("\n");
	        long m = l+60;

	                for(;l<=m;){
	                long k =      obj.getMemoryValue(l);
	                //String str = Long.toHexString(k);
	                //String strn = Long.toHexString(l);
	                String strf=String.format("%08X",k);
	                String strnf=String.format("%08X",l);
	              currView=("0x"+strnf+ "\t" +  "\t" + "0x"+strf+"\n");
	              memView=memView+currView;
	                l=l+4;
	                }
	                home.MemTA.setText("Address"+"\t"+"\t"+"Data"+"\n"+memView);
	   dispose();
}//GEN-LAST:event_ReadBtnActionPerformed

        private void WriteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteBtnActionPerformed
	String mem=MemTF.getText();
	String data =DataTF.getText();
	    	long l= Long.parseLong(mem,16);
	long m = Long.parseLong(data,16);
	
	// System.out.println("I'm in load memory on write "+l+" "+m);
	    obj.loadMemory(l, m);
dispose();
}//GEN-LAST:event_WriteBtnActionPerformed

	    /**
	    * @param args the command line arguments
	    */
	    public static void main(String args[]) {
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new MemInputButton().setVisible(true);
	            }
	        });
	    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DataTF;
    private javax.swing.JTextField MemTF;
    private javax.swing.JButton ReadBtn;
    private javax.swing.JButton WriteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

	}


